version: '3.8'

services:
  registrar:
    image: keylime_registrar:latest
    container_name: keylime-registrar
    restart: unless-stopped
    ports:
      - "8890:8890"
      - "8891:8891"
    volumes:
      - keylime-data:/var/lib/keylime
    networks:
      - keylime-network

  verifier:
    image: keylime_verifier:latest
    container_name: keylime-verifier
    restart: unless-stopped
    ports:
      - "8880:8880"
      - "8881:8881"
    volumes:
      - keylime-data:/var/lib/keylime
    depends_on:
      - registrar
    networks:
      - keylime-network

  # Tenant is more of a client than a continuously running service
  # It's included here for completeness but typically runs on-demand
  tenant:
    image: keylime_tenant:latest
    container_name: keylime-tenant
    # Command can be customized when running tenant commands
    # Default is just to sleep so container stays up for inspection
    command: tail -f /dev/null
    volumes:
      - keylime-data:/var/lib/keylime
    depends_on:
      - registrar
      - verifier
    networks:
      - keylime-network
    profiles:
      - tenant  # Only starts when explicitly included with --profile tenant

networks:
  keylime-network:
    driver: bridge

volumes:
  keylime-data:
    driver: local