FROM _source_keylime_base_digest_ AS keylime_registrar
LABEL version="_version_" description="Keylime Registrar - Bootstrapping and Maintaining Trust in the Cloud"
MAINTAINER Keylime Team <main@keylime.groups.io>

EXPOSE 8890
EXPOSE 8891

ENTRYPOINT ["keylime_registrar"]
