##############################################################################
# keylime TPM 2.0 Dockerfile
#
# This file is for automatic test running of Keylime.
# It is not recommended for use beyond testing scenarios.
##############################################################################

FROM fedora:30
MAINTAINER Luke Hinds <lhinds@redhat.com>
LABEL version="5.0.1" description="Keylime - Bootstrapping and Maintaining Trust in the Cloud"

ENV container docker
# environment variables
ARG BRANCH=master

ENV container docker
ENV HOME /root
ENV KEYLIME_HOME ${HOME}/keylime
ENV TPM_HOME ${HOME}/swtpm2

# Packaged dependencies
RUN dnf -y update
RUN dnf -y install dnf-plugins-core --allowerasing
RUN dnf -y install git \
           dbus-devel \
           openssl-devel \
           python3-devel \
           python3-pip \
           python3-setuptools \
           python3-tornado \
           python3-virtualenv \
           python3-zmq \
           python3-yaml \
           python3-dbus \
           python3-m2crypto \
           python3-cryptography \
           procps \
           libtool \
           tpm2-tss \
           tpm2-tools \
           tpm2-abrmd \
           gcc \
           make \
           automake \
           redhat-rpm-config \
           libselinux-python3 \
           gnulib \
           glib2-devel \
           glib2-static \
           uthash-devel \
           wget \
           which

RUN dnf clean all

RUN cd "/lib/systemd/system/sysinit.target.wants/"; \
    for i in *; do [ $i = systemd-tmpfiles-setup.service ] || rm -f "$i"; done

RUN rm -f /lib/systemd/system/multi-user.target.wants/* \
    /etc/systemd/system/*.wants/* \
    /lib/systemd/system/local-fs.target.wants/* \
    /lib/systemd/system/sockets.target.wants/*udev* \
    /lib/systemd/system/sockets.target.wants/*initctl* \
    /lib/systemd/system/basic.target.wants/* \
    /lib/systemd/system/anaconda.target.wants/*

RUN systemctl set-default multi-user.target
ENV init /lib/systemd/systemd


# Build and install TPM 2.0 simulator
WORKDIR ${TPM_HOME}
RUN wget --content-disposition http://sourceforge.net/projects/ibmswtpm2/files/ibmtpm1119.tar.gz/download
RUN tar -zxvf ibmtpm1119.tar.gz
WORKDIR ${TPM_HOME}/src
RUN make
RUN install -c tpm_server /usr/local/bin/tpm_server

VOLUME [ "/sys/fs/cgroup" ]

ENTRYPOINT ["/lib/systemd/systemd"]
