FROM _source_keylime_base_digest_ AS keylime_verifier
LABEL version="_version_" description="Keylime Verifier - Bootstrapping and Maintaining Trust in the Cloud"
MAINTAINER Keylime Team <main@keylime.groups.io>

RUN --mount=target=/keylime,type=bind,source=.,rw \
    cd /keylime && ./installer.sh -o

EXPOSE 8880
EXPOSE 8881

ENTRYPOINT ["keylime_verifier"]
