FROM keylime_base:latest
LABEL version="_version_" description="Keylime Verifier - Bootstrapping and Maintaining Trust in the Cloud"
LABEL maintainer="Keylime Team <main@keylime.groups.io>"

RUN --mount=target=/keylime,type=bind,source=.,rw \
    cd /keylime && ./installer.sh -o

EXPOSE 8880
EXPOSE 8881

ENTRYPOINT ["keylime_verifier"]