#!/bin/bash

pkill -x tpm_server

export TPM_PATH=~/.tpm0/

mkdir -p ${TPM_PATH}

# Initialize tpm-server

rm -rf ${TPM_PATH} 
mkdir -p ${TPM_PATH}
chmod 700 ${TPM_PATH}

echo -n "TPM Initializing..."
 
# Start server
tpm_serverd 

# Stop server
pkill -x tpm_server

# Restart server
tpm_serverd 

# Stop server now that initialization is complete
pkill -x tpm_server

echo "DONE"

