FROM quay.io/fedora/fedora@sha256:66efce8dd5269d1aaa3d6b8f706029e12c29196e75f30272fb49a1090c7c18b8 AS keylime_base
LABEL version="_version_" description="Keylime Base - Only used as an base image for derived packages"
MAINTAINER Keylime Team <main@keylime.groups.io>

RUN dnf -y install \
    awk \
    dnf-plugins-core \
    efivar-devel \
    efivar-libs \
    git \
    nc \
    python3-PyMySQL \
    python3-jinja2 \
    python3-psycopg2 \
    tpm2-tools
