name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      continue-on-error: true
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for reporting your first issue. If the issue relates to a change you intend to work on, please ask that someone assign it to you.'
        pr-message: 'Thanks for your PR. Please check the CI jobs to make sure the build passes and fix any failures. If you have any questions, please ask and many thanks for your contribution!'
