name: Create PR updating containers base image

on:
  workflow_dispatch:
    branches:
      - master
  schedule:
    - cron: "0 0 1 * *"

env:
  FEDORA_IMAGE: quay.io/fedora/fedora
  TAG: latest
  IMAGE_BASE: quay.io/keylime

jobs:
  update-base-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Install skopeo and jq
        run: sudo apt-get install -y skopeo jq

      - name: Get hash of the latest stable version of Fedora
        run: echo "FEDORA_HASH=$(skopeo inspect docker://${{ env.FEDORA_IMAGE }}:${{ env.TAG }} | jq '.Digest')" >> "$GITHUB_ENV"

      - name: Update the Dockerfile template and CI Dockerfile
        run: |
          sed -i "s#\(FROM \)[^ ]*#\1${{ env.FEDORA_IMAGE }}@${{ env.FEDORA_HASH }}#" docker/release/base/Dockerfile.in
          sed -i "s#\(FROM \).*#\1${{ env.FEDORA_IMAGE }}@${{ env.FEDORA_HASH }}#" docker/ci/Dockerfile

      - name: Get current date for message
        id: date
        run: echo "DATE=$(date +"%Y-%m-%d")" >> "$GITHUB_ENV"

      - name: Create pull request
        uses: peter-evans/create-pull-request@d121e62763d8cc35b5fb1710e887d6e69a52d3a4
        with:
          add-paths: |
            docker/release/base/Dockerfile.in
            docker/ci/Dockerfile
          title: "[Automatic] Update Keylime base image (${{ env.DATE }})"
          signoff: true
          body: |
            Automatically update the Keylime base image using:

            Base image: ${{ env.FEDORA_IMAGE }}@${{ env.FEDORA_HASH }}
          commit-message: |
            [Automatic] Update Keylime base image ${{ env.DATE }}

            Automatically update the Keylime base image using:

            Base image: ${{ env.FEDORA_IMAGE }}@${{ env.FEDORA_HASH }}

